export const DOI_MAU = 'DOI_MAU'
export const DOI_CHU = 'DOI_CHU'
export const FETCH_DATA_BY_SAGA = 'FETCH_DATA_BY_SAGA'
export const FETCH_DATA_BY_SAGA_ALERT_OK = 'FETCH_DATA_BY_SAGA_ALERT_OK'
export const FETCH_DATA_BY_SAGA_ALERT_FAIL = 'FETCH_DATA_BY_SAGA_ALERT_FAIL'
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID'

// trello
export const GET_DATA_TRELLO = 'GET_DATA_TRELLO'
export const UPDATE_DATA_TRELLO = 'UPDATE_DATA_TRELLO'
